// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCn_Fxh-d84cLcVu8pzTJ3YFoGNBSxiK-k',
    appId: '1:137729617710:web:0d33e6eb5b51f01cb854bf',
    messagingSenderId: '137729617710',
    projectId: 'widget-game-ea447',
    authDomain: 'widget-game-ea447.firebaseapp.com',
    storageBucket: 'widget-game-ea447.firebasestorage.app',
    measurementId: 'G-7H4HEHE9D3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBTOVvSADrf5yVq2Xn-v0E-yPex4AS3kQ',
    appId: '1:137729617710:android:6aca0abdd852ce05b854bf',
    messagingSenderId: '137729617710',
    projectId: 'widget-game-ea447',
    storageBucket: 'widget-game-ea447.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcsWYxBVu7hXRnE1Twbvw1UPWnhwznPkI',
    appId: '1:137729617710:ios:7e10a27004ec145db854bf',
    messagingSenderId: '137729617710',
    projectId: 'widget-game-ea447',
    storageBucket: 'widget-game-ea447.firebasestorage.app',
    iosBundleId: 'com.example.widgetGame',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcsWYxBVu7hXRnE1Twbvw1UPWnhwznPkI',
    appId: '1:137729617710:ios:7e10a27004ec145db854bf',
    messagingSenderId: '137729617710',
    projectId: 'widget-game-ea447',
    storageBucket: 'widget-game-ea447.firebasestorage.app',
    iosBundleId: 'com.example.widgetGame',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCn_Fxh-d84cLcVu8pzTJ3YFoGNBSxiK-k',
    appId: '1:137729617710:web:59620727ada146ecb854bf',
    messagingSenderId: '137729617710',
    projectId: 'widget-game-ea447',
    authDomain: 'widget-game-ea447.firebaseapp.com',
    storageBucket: 'widget-game-ea447.firebasestorage.app',
    measurementId: 'G-Q5856YY4ZX',
  );
}
